train_input_data_path: "../data/urdu/train/train_cleaned.tsv"
dev_input_data_path: "../data/urdu/dev/urdu_dev_new.tsv"
dev_gold_path: "../data/urdu/dev/urdu_dev_golds.tsv"
test_input_data_path: false
vector_type: "bow_only"
classifier: "dt"
output_dir: "../outputs/urdu_test"
predictions_file: "urdu_bow_dt_predictions.tsv"
results_dir: "../results"
score_file: "urdu_bow_dt_scores.out"
random_over_under_sample: false
urdu: true