train_input_data_path: "../data/eng/train/eng_train_new.tsv"
dev_input_data_path: "../data/eng/dev/eng_dev_combined.tsv"
dev_gold_path: "../data/eng/dev/goldstandard_dev_2022.tsv"
test_input_data_path: false
vector_type: "pretrained"
classifier: "dt"
pretrained_model: "word2vec-google-news-300"
output_dir: "../outputs/D3"
predictions_file: "googlePt_bal_dt_predictions.tsv"
results_dir: "../results"
score_file: "D3_googlePt_bal_dt_scores.out"
random_over_under_sample: true
