train_input_data_path: "../data/eng/train/eng_train_new.tsv"
dev_input_data_path: "../data/eng/dev/eng_dev_combined.tsv"
dev_gold_path: "../data/eng/dev/goldstandard_dev_2022.tsv"
test_input_data_path: false
vector_type: "bow_only"
classifier: "dtboost"
output_dir: "../outputs/D3"
predictions_file: "neg_bow_bal_dtBoost_predictions.tsv"
results_dir: "../results"
score_file: "D3_neg_bow_bal_dtBoost_scores.out"
negation: "true"
random_over_under_sample: true
