train_input_data_path: "../data/eng/train/eng_train_new.tsv"
dev_input_data_path: "../data/eng/dev/eng_dev_combined.tsv"
dev_gold_path: "../data/eng/dev/goldstandard_dev_2022.tsv"
test_input_data_path: false
vector_type: "bow_only"
classifier: "roberta"
output_dir: "../outputs/roberta_test"
predictions_file: "roberta_predictions.tsv"
results_dir: "../results"
score_file: "roberta_scores.out"
random_over_under_sample: false
